# Generated by Django 4.2.9 on 2024-01-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fixed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=6)),
                ("provider_name", models.CharField(max_length=50)),
                ("provider_id", models.IntegerField()),
                ("period", models.CharField(max_length=7)),
                (
                    "p25_download_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "p75_download_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
            ],
        ),
    ]
