# Generated by Django 4.2.9 on 2024-01-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speed_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixed",
            name="provider_name",
            field=models.CharField(max_length=100),
        ),
    ]
