# Generated by Django 4.2.9 on 2024-01-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speed_test", "0002_alter_fixed_provider_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=6)),
                ("provider_name", models.CharField(max_length=100)),
                ("provider_id", models.IntegerField()),
                ("period", models.CharField(max_length=7)),
                (
                    "p25_download_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "p75_download_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
            ],
        ),
    ]
