# Generated by Django 4.2.9 on 2024-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speed_test", "0003_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=7)),
                (
                    "mobile_median_download_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "mobile_median_upload_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("mobile_latency", models.IntegerField()),
                (
                    "fixed_median_download_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "fixed_median_upload_mbps",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("fixed_latency", models.IntegerField()),
            ],
        ),
    ]
